[package]
name = "project"
version = "0.1.0"
authors = ["muhammadmuneeb264 <muhammadmuneeb264@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
muneeb_function = "0.1.1"
